# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
