# Generated by Django 2.0.3 on 2018-03-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarcalendar', '0002_auto_20180303_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarrequest',
            name='description',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
