# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarcalendar', '0001_initial'),
        ('users', '0004_userprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cal_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarcalendar.CalendarRequest'),
            preserve_default=False,
        ),
    ]
