# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0002_auto_20180223_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.CharField(choices=[('UNC-CH', 'UNC Chapel Hill')], default='UNC-CH', max_length=30),
        ),
    ]
