# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0006_auto_20180301_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment_total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_total',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='test_total',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
