# Generated by Django 2.0.3 on 2018-03-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0007_auto_20180303_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
