# Generated by Django 2.0.3 on 2018-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0008_auto_20180315_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseimage',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
